"use client";

import { useMemo, useState } from "react";

type View = "home" | "studentLogin" | "student" | "worker" | "admin";
type Status = "Pending" | "In Progress" | "Completed" | "Needs Work Again";
type Grievance = { id:string; room:string; block:string; category:string; subject:string; description:string; status:Status; createdAt:Date; worker?:string };

const categories=["Electrical issue","Light not working","Fan not working","Switch or socket problem","Water leakage","Plumbing issue","Bathroom issue","Toilet issue","Drainage problem","Wi-Fi / Internet","Furniture damaged","Bed issue","Door issue","Window issue","Cleaning issue","Garbage issue","Pest / insects","Security issue","Room maintenance","Other"];

const initial:Grievance[]=[
{id:"GRV-A-104-001",block:"A",room:"104",category:"Electrical issue",subject:"Fan not working",description:"The ceiling fan is not turning on even after changing the regulator.",status:"Pending",createdAt:new Date(Date.now()-5*86400000)},
{id:"GRV-B-203-002",block:"B",room:"203",category:"Water leakage",subject:"Water leaking ceiling",description:"Water is dripping near the study table.",status:"In Progress",createdAt:new Date(Date.now()-3*86400000),worker:"Maintenance Team"},
{id:"GRV-C-108-003",block:"C",room:"108",category:"Wi-Fi / Internet",subject:"Wi-Fi unavailable",description:"No internet connection in the room since yesterday.",status:"Pending",createdAt:new Date(Date.now()-86400000)}
];

function priority(g:Grievance){const d=Math.floor((Date.now()-g.createdAt.getTime())/86400000);if(["Security issue","Electrical issue"].includes(g.category)||d>=7)return"Critical";if(d>=4)return"High";if(d>=2)return"Medium";return"Low"}

export default function Home(){
const[view,setView]=useState<View>("home");const[grievances,setGrievances]=useState(initial);const[block,setBlock]=useState("A");const[floor,setFloor]=useState("Ground");const[room,setRoom]=useState("1");const[category,setCategory]=useState(categories[0]);const[search,setSearch]=useState("");const[subject,setSubject]=useState("");const[description,setDescription]=useState("");const[notice,setNotice]=useState("");const[filter,setFilter]=useState("");

const rooms=useMemo(()=>{const prefix=floor==="Ground"?"":floor==="First"?"1":floor==="Second"?"2":"3";return Array.from({length:10},(_,i)=>prefix?prefix+String(i+1).padStart(2,"0"):String(i+1))},[floor]);
const active=grievances.filter(g=>g.status!=="Completed");

function submit(e:React.FormEvent){e.preventDefault();if(!subject.trim()||!description.trim())return;const id="GRV-"+block+"-"+room+"-"+String(grievances.length+1).padStart(3,"0");setGrievances([{id,block,room,category,subject,description,status:"Pending",createdAt:new Date()},...grievances]);setSubject("");setDescription("");setNotice("Grievance submitted successfully. Report ID: "+id)}
function complete(id:string){const worker=window.prompt("Enter your name before closing this grievance:");if(!worker?.trim())return;setGrievances(gs=>gs.map(g=>g.id===id?{...g,status:"Completed",worker}:g));setNotice("Marked completed. The student will see this after real notifications are connected.")}
function reopen(id:string){setGrievances(gs=>gs.map(g=>g.id===id?{...g,status:"Needs Work Again"}:g));setNotice("Grievance reopened and returned to the worker queue.")}
function googleLogin(){setNotice("Google login is not configured yet. We need to connect Google OAuth before real student sign-in can work.")}

return <main>
<nav className="nav"><button className="brand" onClick={()=>setView("home")}><span>✓</span> HostelResolve</button><div className="navlinks"><button onClick={()=>setView("home")}>Home</button><button onClick={()=>setView("worker")}>Worker</button><button onClick={()=>setView("admin")}>Admin</button></div></nav>
{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}

{view==="home"&&<section className="hero"><div className="eyebrow">HOSTEL GRIEVANCE MANAGEMENT</div><h1>How would you like to<br/><em>continue?</em></h1><p>Students sign in with their Google account before reporting an issue. Workers can directly open the pending grievance queue.</p><div className="portal-grid"><button className="portal student" onClick={()=>setView("studentLogin")}><b>🎓</b><span><strong>I am a Student</strong><small>Sign in first, then report and track grievances</small></span><i>→</i></button><button className="portal worker" onClick={()=>setView("worker")}><b>🛠️</b><span><strong>I am a Worker</strong><small>Direct access to pending grievances</small></span><i>→</i></button></div><div className="hero-stats"><span><b>{active.length}</b> Active reports</span><span><b>24h</b> Response target</span><span><b>7 days</b> Archive rule</span></div></section>}

{view==="studentLogin"&&<section className="page"><div className="login-card"><div className="eyebrow">STUDENT ACCESS</div><h2>Sign in to HostelResolve</h2><p>Use your Google account so your grievances are linked to you and only you can track or close them.</p><button className="primary" type="button" onClick={googleLogin}>G &nbsp; Continue with Google</button><button className="back" onClick={()=>setView("home")}>← Back</button><small>Google authentication is being connected. This button is not yet a real Google sign-in.</small></div></section>}

{view==="student"&&<section className="page"><div className="page-head"><div><div className="eyebrow">STUDENT PORTAL</div><h2>Submit a grievance</h2><p>Choose your room and tell us what needs attention.</p></div></div><form className="form-card" onSubmit={submit}><div className="step"><span>1</span><div><h3>Where is the problem?</h3><div className="form-grid"><label>Block<select value={block} onChange={e=>setBlock(e.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label>Floor<select value={floor} onChange={e=>{setFloor(e.target.value);setRoom("1")}}><option>Ground</option><option>First</option><option>Second</option><option>Third</option></select></label><label>Room<select value={room} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r}>{r}</option>)}</select></label></div></div></div><div className="step"><span>2</span><div className="wide"><h3>What is the issue?</h3><input placeholder="Search common issues..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="chips">{categories.filter(c=>c.toLowerCase().includes(search.toLowerCase())).map(c=><button type="button" key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><label>Selected category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Short subject (4–5 words)<input required maxLength={70} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. Water leaking from ceiling"/></label></div></div><div className="step"><span>3</span><div className="wide"><h3>Explain the problem</h3><textarea required minLength={10} maxLength={1200} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explain the problem clearly..."/><div className="helper">{description.trim().split(/\s+/).filter(Boolean).length} words · Recommended up to 200 words</div></div></div><button className="primary" type="submit">Submit grievance →</button></form><h3 className="section-title">Your reports</h3><div className="report-list">{grievances.map(g=><Report key={g.id} g={g} onReopen={reopen}/>)}</div></section>}

{view==="worker"&&<section className="page"><div className="page-head"><div><div className="eyebrow">WORKER PORTAL</div><h2>Pending grievance queue</h2><p>No Google account is required for workers.</p></div></div><div className="toolbar"><input placeholder="Search room, issue or report ID..." value={filter} onChange={e=>setFilter(e.target.value)}/><span>{active.length} active</span></div><div className="queue">{[...active].filter(g=>(g.room+g.subject+g.id+g.category).toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>a.createdAt.getTime()-b.createdAt.getTime()).map(g=><article className="job" key={g.id}><div className={"priority "+priority(g).toLowerCase()}>{priority(g)}</div><div className="job-main"><div className="job-top"><b>{g.subject}</b><span>{g.id}</span></div><p>{g.description}</p><div className="meta"><span>🏢 Block {g.block}</span><span>🚪 Room {g.room}</span><span>🕒 {Math.floor((Date.now()-g.createdAt.getTime())/86400000)} day(s) pending</span><span>{g.status}</span></div></div><div className="job-actions"><button onClick={()=>setGrievances(gs=>gs.map(x=>x.id===g.id?{...x,status:"In Progress"}:x))}>Start work</button><button className="complete" onClick={()=>complete(g.id)}>Complete</button></div></article>)}</div></section>}

{view==="admin"&&<section className="page"><div className="page-head"><div><div className="eyebrow">ADMIN OVERVIEW</div><h2>Hostel operations at a glance</h2><p>Demo analytics until the database is connected.</p></div></div><div className="metrics"><Metric label="Total reports" value={grievances.length}/><Metric label="Pending" value={grievances.filter(g=>g.status==="Pending").length}/><Metric label="Needs work again" value={grievances.filter(g=>g.status==="Needs Work Again").length}/><Metric label="Completed" value={grievances.filter(g=>g.status==="Completed").length}/></div></section>}
</main>}

function Report({g,onReopen}:{g:Grievance;onReopen:(id:string)=>void}){return <article className="report"><div><span className={"status "+g.status.toLowerCase().replaceAll(" ","-")}>{g.status}</span><h4>{g.subject}</h4><p>{g.block} Block · Room {g.room} · {g.category}</p>{g.worker&&<small>Completed by: {g.worker}</small>}</div>{g.status==="Completed"&&<div className="report-actions"><button onClick={()=>onReopen(g.id)}>Not satisfied</button><button className="close">Satisfied ✓</button></div>}</article>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}