"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type View = "home" | "studentLogin" | "student" | "workerLogin" | "worker" | "admin";
type Status = "Pending" | "In Progress" | "Awaiting Confirmation" | "Completed" | "Needs Work Again";
type Grievance = { id:string; room:string; block:string; category:string; subject:string; description:string; status:Status; createdAt:Date; worker?:string; studentEmail?:string };

const categories=["Electrical issue","Light not working","Fan not working","Switch or socket problem","Water leakage","Plumbing issue","Bathroom issue","Toilet issue","Drainage problem","Wi-Fi / Internet","Furniture damaged","Bed issue","Door issue","Window issue","Cleaning issue","Garbage issue","Pest / insects","Security issue","Room maintenance","Other"];

const initial:Grievance[]=[
{id:"GRV-A-104-001",block:"A",room:"104",category:"Electrical issue",subject:"Fan not working",description:"The ceiling fan is not turning on even after changing the regulator.",status:"Pending",createdAt:new Date(Date.now()-5*86400000)},
{id:"GRV-B-203-002",block:"B",room:"203",category:"Water leakage",subject:"Water leaking ceiling",description:"Water is dripping near the study table.",status:"In Progress",createdAt:new Date(Date.now()-3*86400000),worker:"Maintenance Team"},
{id:"GRV-C-108-003",block:"C",room:"108",category:"Wi-Fi / Internet",subject:"Wi-Fi unavailable",description:"No internet connection in the room since yesterday.",status:"Pending",createdAt:new Date(Date.now()-86400000)}
];

function priority(g:Grievance){const d=Math.floor((Date.now()-g.createdAt.getTime())/86400000);if(["Security issue","Electrical issue"].includes(g.category)||d>=7)return"Critical";if(d>=4)return"High";if(d>=2)return"Medium";return"Low"}

export default function Home(){
const[view,setView]=useState<View>("home");const[grievances,setGrievances]=useState(initial);const[block,setBlock]=useState("A");const[floor,setFloor]=useState("Ground");const[room,setRoom]=useState("1");const[category,setCategory]=useState(categories[0]);const[search,setSearch]=useState("");const[subject,setSubject]=useState("");const[description,setDescription]=useState("");const[notice,setNotice]=useState("");const[filter,setFilter]=useState("");const[userEmail,setUserEmail]=useState("");const[userName,setUserName]=useState("");const[dateFilter,setDateFilter]=useState("all");const[fromDate,setFromDate]=useState("");const[toDate,setToDate]=useState("");
const workerEmails=(process.env.NEXT_PUBLIC_WORKER_EMAILS||"").split(",").map(e=>e.trim().toLowerCase()).filter(Boolean);
const isWorker=!!userEmail&&workerEmails.includes(userEmail.toLowerCase());

useEffect(()=>{let mounted=true;supabase.auth.getUser().then(({data})=>{if(!mounted)return;const user=data.user;if(user){setUserEmail(user.email||"");setUserName(String(user.user_metadata?.full_name||user.user_metadata?.name||user.email||"Student"));if(new URLSearchParams(window.location.search).get("student")==="1")setView("student")}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{const user=session?.user;if(user){setUserEmail(user.email||"");setUserName(String(user.user_metadata?.full_name||user.user_metadata?.name||user.email||"Student"))}else{setUserEmail("");setUserName("");if(view==="student")setView("home")}});return()=>{mounted=false;subscription.unsubscribe()}},[]);

const rooms=useMemo(()=>{const prefix=floor==="Ground"?"":floor==="First"?"1":floor==="Second"?"2":"3";return Array.from({length:10},(_,i)=>prefix?prefix+String(i+1).padStart(2,"0"):String(i+1))},[floor]);
const active=grievances.filter(g=>g.status!=="Completed");
const studentReports=grievances.filter(g=>g.studentEmail===userEmail);
const toDayKey=(d:Date)=>d.toISOString().slice(0,10);
const filteredWorkerReports=[...active].filter(g=>{const q=(g.room+g.subject+g.id+g.category).toLowerCase().includes(filter.toLowerCase());if(!q)return false;const day=toDayKey(g.createdAt);const today=new Date();today.setHours(0,0,0,0);const created=new Date(g.createdAt);created.setHours(0,0,0,0);if(dateFilter==="today")return created.getTime()===today.getTime();if(dateFilter==="week"){const start=new Date(today);start.setDate(start.getDate()-6);return created>=start&&created<=today}if(dateFilter==="month")return created.getFullYear()===today.getFullYear()&&created.getMonth()===today.getMonth();if(dateFilter==="custom"){return (!fromDate||day>=fromDate)&&(!toDate||day<=toDate)}return true}).sort((a,b)=>a.createdAt.getTime()-b.createdAt.getTime());

async function submit(e:React.FormEvent){e.preventDefault();if(!userEmail){setView("studentLogin");return}if(!subject.trim()||!description.trim())return;const id="GRV-"+block+"-"+room+"-"+String(grievances.length+1).padStart(3,"0");setGrievances([{id,block,room,category,subject,description,status:"Pending",createdAt:new Date(),studentEmail:userEmail},...grievances]);setSubject("");setDescription("");setNotice("Grievance submitted successfully. Report ID: "+id)}
function finishWork(id:string){if(!isWorker){setView("workerLogin");return}setGrievances(gs=>gs.map(g=>g.id===id?{...g,status:"Awaiting Confirmation",worker:userName||userEmail}:g));setNotice("Work marked done. It is now waiting for the student to confirm the resolution.")}
function confirmResolved(id:string){setGrievances(gs=>gs.map(g=>g.id===id?{...g,status:"Completed"}:g));setNotice("Resolution confirmed. The report is now closed.")}
function reopen(id:string){setGrievances(gs=>gs.map(g=>g.id===id?{...g,status:"Needs Work Again"}:g));setNotice("Grievance reopened and returned to the worker queue.")}
function openWorker(){if(!userEmail){setView("workerLogin");return}if(!isWorker){setNotice("This Google account is not authorised as a worker.");return}setView("worker")}
async function googleLogin(){setNotice("");const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/auth/callback"}});if(error)setNotice("Could not start Google login: "+error.message)}
async function logout(){await supabase.auth.signOut();setView("home");setNotice("You have been signed out.")}

return <main>
<nav className="nav"><button className="brand" onClick={()=>setView("home")}><span>✓</span> HostelResolve</button><div className="navlinks"><button onClick={()=>setView("home")}>Home</button>{!userEmail&&<><button onClick={()=>setView("studentLogin")}>Student</button><button onClick={()=>setView("workerLogin")}>Worker</button></>}{userEmail&&!isWorker&&<button onClick={()=>setView("student")}>My reports</button>}{isWorker&&<button onClick={openWorker}>Worker queue</button>}{isWorker&&<button onClick={()=>setView("admin")}>Admin</button>}{userEmail&&<button className="worker-login" onClick={logout}>Logout</button>}</div></nav>
{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}

{view==="home"&&<section className="hero"><div className="eyebrow">HOSTEL GRIEVANCE MANAGEMENT</div><h1>How would you like to<br/><em>continue?</em></h1><p>Students sign in with Google before reporting an issue. Workers can directly open the pending grievance queue.</p><div className="portal-grid"><button className="portal student" onClick={()=>setView(userEmail?"student":"studentLogin")}><b>🎓</b><span><strong>I am a Student</strong><small>{userEmail?"Continue as "+userName:"Sign in first, then report and track grievances"}</small></span><i>→</i></button><button className="portal worker" onClick={openWorker}><b>🛠️</b><span><strong>I am a Worker</strong><small>Authorised workers sign in before opening the queue</small></span><i>→</i></button></div><div className="hero-stats"><span><b>{active.length}</b> Active reports</span><span><b>24h</b> Response target</span><span><b>7 days</b> Archive rule</span></div></section>}

{view==="studentLogin"&&<section className="page"><div className="login-card"><div className="eyebrow">STUDENT ACCESS</div><h2>{userEmail?"You are already signed in":"Sign in to HostelResolve"}</h2><p>{userEmail?userName+" · "+userEmail:"Use your Google account so your grievances are linked to you and only you can track or close them."}</p>{userEmail?<button className="primary" type="button" onClick={()=>setView("student")}>Continue to Student Portal →</button>:<button className="primary" type="button" onClick={googleLogin}>G &nbsp; Continue with Google</button>}<button className="back" onClick={()=>setView("home")}>← Back</button><small>{userEmail?"Google authentication is active for this session.":"You will be redirected to Google and then safely returned to HostelResolve."}</small></div></section>}

{view==="workerLogin"&&<section className="page"><div className="login-card"><div className="eyebrow">WORKER ACCESS</div><h2>{userEmail?(isWorker?"Worker access granted":"Worker access restricted"):"Sign in as an authorised worker"}</h2><p>{userEmail?(isWorker?userName+" · "+userEmail:"This account is not on the authorised worker list."):"Workers must sign in with an authorised Google account before they can change report status."}</p>{!userEmail?<button className="primary" type="button" onClick={googleLogin}>G &nbsp; Continue with Google</button>:isWorker?<button className="primary" type="button" onClick={()=>setView("worker")}>Open Worker Queue →</button>:<><button className="primary" type="button" onClick={logout}>Use another account</button><button className="back" onClick={()=>setView("home")}>← Back</button></>}<small>Workers can mark work as done, but only the student can finally close a grievance.</small></div></section>}

{view==="student"&&<section className="page"><div className="page-head"><div><div className="eyebrow">STUDENT PORTAL</div><h2>Submit a grievance</h2><p>{userEmail?"Signed in as "+userName+" · "+userEmail:"Choose your room and tell us what needs attention."}</p></div><button className="worker-login" onClick={logout}>Logout</button></div><form className="form-card" onSubmit={submit}><div className="step"><span>1</span><div><h3>Where is the problem?</h3><div className="form-grid"><label>Block<select value={block} onChange={e=>setBlock(e.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label>Floor<select value={floor} onChange={e=>{setFloor(e.target.value);setRoom("1")}}><option>Ground</option><option>First</option><option>Second</option><option>Third</option></select></label><label>Room<select value={room} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r}>{r}</option>)}</select></label></div></div></div><div className="step"><span>2</span><div className="wide"><h3>What is the issue?</h3><input placeholder="Search common issues..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="chips">{categories.filter(c=>c.toLowerCase().includes(search.toLowerCase())).map(c=><button type="button" key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><label>Selected category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Short subject (4–5 words)<input required maxLength={70} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. Water leaking from ceiling"/></label></div></div><div className="step"><span>3</span><div className="wide"><h3>Explain the problem</h3><textarea required minLength={10} maxLength={1200} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explain the problem clearly..."/><div className="helper">{description.trim().split(/\s+/).filter(Boolean).length} words · Recommended up to 200 words</div></div></div><button className="primary" type="submit">Submit grievance →</button></form><h3 className="section-title">Your reports</h3><div className="report-list">{studentReports.length?studentReports.map(g=><Report key={g.id} g={g} onReopen={reopen} onConfirm={confirmResolved}/>):<div className="empty">Your submitted reports will appear here.</div>}</div></section>}

{view==="worker"&&isWorker&&<section className="page"><div className="page-head"><div><div className="eyebrow">WORKER PORTAL</div><h2>Pending grievance queue</h2><p>Signed in as {userName||userEmail}. Only authorised workers can update jobs.</p></div></div><div className="toolbar filter-toolbar"><input placeholder="Search room, issue or report ID..." value={filter} onChange={e=>setFilter(e.target.value)}/><select value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">All dates</option><option value="today">Today</option><option value="week">Last 7 days</option><option value="month">This month</option><option value="custom">Custom range</option></select>{dateFilter==="custom"&&<><input type="date" aria-label="From date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input type="date" aria-label="To date" value={toDate} onChange={e=>setToDate(e.target.value)}/></>}<span>{filteredWorkerReports.length} shown</span></div><div className="queue">{filteredWorkerReports.map(g=><article className="job" key={g.id}><div className={"priority "+priority(g).toLowerCase()}>{priority(g)}</div><div className="job-main"><div className="job-top"><b>{g.subject}</b><span>{g.id}</span></div><p>{g.description}</p><div className="meta"><span>🏢 Block {g.block}</span><span>🚪 Room {g.room}</span><span>📅 {toDayKey(g.createdAt)}</span><span>{g.status}</span>{g.worker&&<span>🛠️ {g.worker}</span>}</div></div><div className="job-actions">{g.status!=="Awaiting Confirmation"&&<button onClick={()=>setGrievances(gs=>gs.map(x=>x.id===g.id?{...x,status:"In Progress",worker:userName||userEmail}:x))}>Start work</button>}{g.status==="In Progress"&&<button className="complete" onClick={()=>finishWork(g.id)}>Request closure</button>}{g.status==="Awaiting Confirmation"&&<span className="awaiting">Waiting for student</span>}</div></article>)}</div></section>}

{view==="admin"&&<section className="page"><div className="page-head"><div><div className="eyebrow">ADMIN OVERVIEW</div><h2>Hostel operations at a glance</h2><p>Demo analytics until the database is connected.</p></div></div><div className="metrics"><Metric label="Total reports" value={grievances.length}/><Metric label="Pending" value={grievances.filter(g=>g.status==="Pending").length}/><Metric label="Needs work again" value={grievances.filter(g=>g.status==="Needs Work Again").length}/><Metric label="Completed" value={grievances.filter(g=>g.status==="Completed").length}/></div></section>}
</main>}

function Report({g,onReopen,onConfirm}:{g:Grievance;onReopen:(id:string)=>void;onConfirm:(id:string)=>void}){return <article className="report"><div><span className={"status "+g.status.toLowerCase().replaceAll(" ","-")}>{g.status}</span><h4>{g.subject}</h4><p>{g.block} Block · Room {g.room} · {g.category}</p>{g.worker&&<small>Handled by: {g.worker}</small>}</div>{g.status==="Awaiting Confirmation"&&<div className="report-actions"><button onClick={()=>onReopen(g.id)}>Not satisfied</button><button className="close" onClick={()=>onConfirm(g.id)}>Resolved ✓</button></div>}</article>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}