"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type View="home"|"studentLogin"|"student"|"workerLogin"|"worker";
type Status="Pending"|"In Progress"|"Awaiting Confirmation"|"Completed"|"Needs Work Again";
type Grievance={id:string;block:string;floor:string;room:string;category:string;subject:string;description:string;status:Status;priority:string;created_at:string;updated_at:string;worker?:string|null;student_id:string;student_email:string};

const categories=["Electrical issue","Light not working","Fan not working","Switch or socket problem","Water leakage","Plumbing issue","Bathroom issue","Toilet issue","Drainage problem","Wi-Fi / Internet","Furniture damaged","Bed issue","Door issue","Window issue","Cleaning issue","Garbage issue","Pest / insects","Security issue","Room maintenance","Other"];
const priorityFor=(category:string)=>["Security issue","Electrical issue"].includes(category)?"Critical":["Water leakage","Plumbing issue","Toilet issue","Drainage problem"].includes(category)?"High":"Medium";
const day=(v:string)=>new Date(v).toLocaleDateString("en-CA");

export default function Home(){
 const [view,setView]=useState<View>("home"),[grievances,setGrievances]=useState<Grievance[]>([]);
 const [portal,setPortal]=useState<"student"|"worker"|null>(null);
 const [block,setBlock]=useState("A"),[floor,setFloor]=useState("Ground"),[room,setRoom]=useState("1"),[category,setCategory]=useState(categories[0]),[search,setSearch]=useState(""),[subject,setSubject]=useState(""),[description,setDescription]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
 const [user,setUser]=useState<{id:string;email:string;name:string}|null>(null);
 const [worker,setWorker]=useState<{id:string;name:string}|null>(null),[workerId,setWorkerId]=useState(""),[workerPin,setWorkerPin]=useState("");
 const [filter,setFilter]=useState(""),[dateFilter,setDateFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("all"),[categoryFilter,setCategoryFilter]=useState("all");

 const rooms=useMemo(()=>{const p=floor==="Ground"?"":floor==="First"?"1":floor==="Second"?"2":"3";return Array.from({length:10},(_,i)=>p?p+String(i+1).padStart(2,"0"):String(i+1))},[floor]);

 async function loadStudent(uid:string){setPortal("student");const {data,error}=await supabase.from("grievances").select("*").eq("student_id",uid).order("created_at",{ascending:false});if(error){setNotice("Database error: "+error.message);return}setGrievances((data||[]) as Grievance[])}
 async function loadWorker(){setPortal("worker");const r=await fetch("/api/worker/reports",{cache:"no-store"});const d=await r.json();if(!r.ok){setNotice(d.error||"Could not load worker queue.");return}setGrievances(d.reports||[])}

 useEffect(()=>{let alive=true;supabase.auth.getUser().then(({data})=>{if(!alive||!data.user)return;const u=data.user;const next={id:u.id,email:u.email||"",name:String(u.user_metadata?.full_name||u.user_metadata?.name||u.email||"Student")};setUser(next);loadStudent(u.id);if(new URLSearchParams(location.search).get("student")==="1")setView("student")});fetch("/api/worker/me",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(d?.worker){setWorker(d.worker);if(!user){} }}).catch(()=>{});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user){const u=s.user;const next={id:u.id,email:u.email||"",name:String(u.user_metadata?.full_name||u.user_metadata?.name||u.email||"Student")};setUser(next);loadStudent(u.id)}else setUser(null)});return()=>{alive=false;subscription.unsubscribe()}},[]);

 const active=grievances.filter(g=>g.status!=="Completed");
 const studentReports=user?grievances.filter(g=>g.student_id===user.id):[];
 const filtered=active.filter(g=>{const q=(g.id+" "+g.room+" "+g.subject+" "+g.category+" "+g.block).toLowerCase().includes(filter.toLowerCase());if(!q)return false;if(statusFilter!=="all"&&g.status!==statusFilter)return false;if(categoryFilter!=="all"&&g.category!==categoryFilter)return false;const now=new Date(),d=new Date(g.created_at);if(dateFilter==="today")return day(g.created_at)===day(now.toISOString());if(dateFilter==="week")return now.getTime()-d.getTime()<=7*86400000;if(dateFilter==="month")return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return true});

 async function submit(e:React.FormEvent){e.preventDefault();if(!user){setView("studentLogin");return}if(!subject.trim()||description.trim().length<10)return;setLoading(true);const id="GRV-"+block+"-"+room+"-"+Date.now().toString().slice(-6)+"-"+Math.random().toString(36).slice(2,5).toUpperCase();const row={id,block,floor,room,category,subject:subject.trim(),description:description.trim(),status:"Pending" as Status,priority:priorityFor(category),student_id:user.id,student_email:user.email};const {data,error}=await supabase.from("grievances").insert(row).select("*").single();setLoading(false);if(error){setNotice("Could not submit: "+error.message);return}setGrievances(gs=>[data as Grievance,...gs]);setSubject("");setDescription("");setNotice("Grievance submitted successfully. Report ID: "+id)}

 async function studentAction(id:string,status:"Completed"|"Needs Work Again"){const {data,error}=await supabase.from("grievances").update({status,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error){setNotice("Could not update report: "+error.message);return}setGrievances(gs=>gs.map(g=>g.id===id?data as Grievance:g));setNotice(status==="Completed"?"Thanks — the report is now closed.":"The report has been reopened and returned to the worker queue.")}

 async function workerAction(id:string,status:"In Progress"|"Awaiting Confirmation"){const r=await fetch("/api/worker/reports",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok){setNotice(d.error||"Could not update report.");return}setGrievances(gs=>gs.map(g=>g.id===id?d.report:g));setNotice(status==="In Progress"?"Job claimed successfully.":"Closure requested. The student must confirm the resolution.")}

 async function workerLogin(e:React.FormEvent){e.preventDefault();setNotice("");setPortal("worker");const r=await fetch("/api/worker/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workerId,workerPin})});const d=await r.json();if(!r.ok){setNotice(d.error||"Invalid Worker ID or PIN.");return}setWorker(d.worker);setWorkerPin("");setView("worker");await loadWorker()}
 async function workerLogout(){await fetch("/api/worker/logout",{method:"POST"});setWorker(null);setPortal(null);setView("home");setGrievances([]);setNotice("Worker session ended.")}
 async function googleLogin(){const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/auth/callback?student=1"}});if(error)setNotice(error.message)}
 async function studentLogout(){await supabase.auth.signOut();setUser(null);setPortal(null);setGrievances([]);setView("home")}

 return <main>
  <nav className={"nav portal-"+(portal||"home")}><button className="brand" onClick={()=>{setPortal(null);setView("home")}}><span>✓</span> HostelResolve</button><div className="navlinks">{portal==="student"&&<><button onClick={()=>setView("student")}>Dashboard</button><button onClick={()=>{setPortal(null);setView("workerLogin")}}>Worker portal</button><button className="worker-login" onClick={studentLogout}>Logout</button></>}{portal==="worker"&&<><button onClick={async()=>{setView("worker");await loadWorker()}}>Worker queue</button><button onClick={()=>{setPortal(null);setView("studentLogin")}}>Student portal</button><button className="worker-login" onClick={workerLogout}>Logout</button></>}{!portal&&<><button onClick={()=>setView("studentLogin")}>Student</button><button onClick={()=>setView("workerLogin")}>Worker</button></>}</div></nav>
  {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}

  {view==="home"&&<section className="hero"><div className="eyebrow">SMART HOSTEL OPERATIONS</div><h1>Report it.<br/><em>Track it. Resolve it.</em></h1><p>A professional grievance workflow with student ownership, authorised worker access and final student confirmation.</p><div className="portal-grid"><button className="portal student" onClick={()=>{setPortal("student");setView(user?"student":"studentLogin")}}><b>🎓</b><span><strong>Student portal</strong><small>{user?"Continue as "+user.name:"Submit, track and confirm your own reports"}</small></span><i>→</i></button><button className="portal worker" onClick={()=>{setPortal("worker");setView(worker?"worker":"workerLogin")}}><b>🛠️</b><span><strong>Worker portal</strong><small>Worker ID + PIN only — no Gmail required</small></span><i>→</i></button></div><div className="hero-stats"><span><b>Private</b> student reports</span><span><b>Tracked</b> status workflow</span><span><b>Verified</b> closure confirmation</span></div></section>}

  {view==="studentLogin"&&<section className="page"><div className="login-card"><div className="eyebrow">STUDENT ACCESS</div><h2>{user?"Welcome back":"Sign in to HostelResolve"}</h2><p>{user?user.name+" · "+user.email:"Use Google to securely link reports to your account. You will only see and manage your own grievances."}</p><button className="primary" onClick={user?()=>{setPortal("student");setView("student")}:googleLogin}>{user?"Open my reports →":"G  Continue with Google"}</button><button className="back" onClick={()=>setView("home")}>← Back</button></div></section>}

  {view==="workerLogin"&&<section className="page"><div className="login-card"><div className="eyebrow">WORKER ACCESS</div><h2>{worker?"Access granted":"Worker sign in"}</h2><p>{worker?"Signed in as "+worker.name:"Workers do not need Gmail. Enter the Worker ID and PIN issued by hostel management."}</p>{worker?<button className="primary" onClick={async()=>{setView("worker");await loadWorker()}}>Open worker queue →</button>:<form className="worker-auth-form" onSubmit={workerLogin}><label>Worker ID<input required value={workerId} onChange={e=>setWorkerId(e.target.value)} placeholder="e.g. ELEC-01"/></label><label>PIN<input required type="password" inputMode="numeric" value={workerPin} onChange={e=>setWorkerPin(e.target.value)} placeholder="Enter your PIN"/></label><button className="primary">Sign in →</button></form>}<button className="back" onClick={()=>setView("home")}>← Back</button></div></section>}

  {view==="student"&&<section className="page"><div className="page-head"><div><div className="eyebrow">STUDENT DASHBOARD</div><h2>Report and track issues</h2><p>{user?"Signed in as "+user.name:""}</p></div></div><div className="metrics student-metrics"><Metric label="Open" value={studentReports.filter(g=>g.status!=="Completed").length}/><Metric label="In progress" value={studentReports.filter(g=>g.status==="In Progress").length}/><Metric label="Awaiting you" value={studentReports.filter(g=>g.status==="Awaiting Confirmation").length}/><Metric label="Resolved" value={studentReports.filter(g=>g.status==="Completed").length}/></div><form className="form-card" onSubmit={submit}><div className="step"><span>1</span><div><h3>Where is the problem?</h3><div className="form-grid"><label>Block<select value={block} onChange={e=>setBlock(e.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label>Floor<select value={floor} onChange={e=>{setFloor(e.target.value);setRoom("1")}}><option>Ground</option><option>First</option><option>Second</option><option>Third</option></select></label><label>Room<select value={room} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r}>{r}</option>)}</select></label></div></div></div><div className="step"><span>2</span><div className="wide"><h3>What is the issue?</h3><input placeholder="Search common issues..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="chips">{categories.filter(c=>c.toLowerCase().includes(search.toLowerCase())).map(c=><button type="button" key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><label>Short subject<input required maxLength={70} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. Water leaking from ceiling"/></label></div></div><div className="step"><span>3</span><div className="wide"><h3>Explain the problem</h3><textarea required minLength={10} maxLength={1200} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explain what happened, where it is and anything that may help the worker..."/><div className="helper">{description.trim().split(/\s+/).filter(Boolean).length} words · Minimum 10 words recommended</div></div></div><button className="primary" disabled={loading}>{loading?"Submitting...":"Submit grievance →"}</button></form><h3 className="section-title">Your reports</h3><div className="report-list">{studentReports.length?studentReports.map(g=><Report key={g.id} g={g} onAction={studentAction}/>):<div className="empty">No reports yet. Your real complaints will appear here after submission.</div>}</div></section>}

  {view==="worker"&&worker&&<section className="page"><div className="page-head"><div><div className="eyebrow">WORKER PORTAL</div><h2>Live grievance queue</h2><p>Signed in as {worker.name}. Jobs are real database records and remain available after refresh.</p></div><button className="worker-login" onClick={loadWorker}>↻ Refresh</button></div><div className="toolbar filter-toolbar"><input placeholder="Search report ID, room, issue..." value={filter} onChange={e=>setFilter(e.target.value)}/><select value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">All dates</option><option value="today">Today</option><option value="week">Last 7 days</option><option value="month">This month</option></select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option><option>Pending</option><option>In Progress</option><option>Needs Work Again</option><option>Awaiting Confirmation</option></select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><span>{filtered.length} shown</span></div><div className="queue">{filtered.length?filtered.map(g=><article className="job" key={g.id}><div className={"priority "+g.priority.toLowerCase()}>{g.priority}</div><div className="job-main"><div className="job-top"><b>{g.subject}</b><span>{g.id}</span></div><p>{g.description}</p><div className="meta"><span>🏢 Block {g.block}</span><span>📍 {g.floor}</span><span>🚪 Room {g.room}</span><span>📅 {day(g.created_at)}</span><span>{g.status}</span>{g.worker&&<span>🛠️ {g.worker}</span>}</div></div><div className="job-actions">{(g.status==="Pending"||g.status==="Needs Work Again")&&<button onClick={()=>workerAction(g.id,"In Progress")}>Start work</button>}{g.status==="In Progress"&&<button className="complete" onClick={()=>workerAction(g.id,"Awaiting Confirmation")}>Request closure</button>}{g.status==="Awaiting Confirmation"&&<span className="awaiting">Waiting for student</span>}</div></article>):<div className="empty">🎉 No complaints match these filters. The queue is clear.</div>}</div></section>}
 </main>
}

function Report({g,onAction}:{g:Grievance;onAction:(id:string,status:"Completed"|"Needs Work Again")=>void}){return <article className="report"><div><span className={"status "+g.status.toLowerCase().replaceAll(" ","-")}>{g.status}</span><h4>{g.subject}</h4><p>Block {g.block} · {g.floor} · Room {g.room} · {g.category}</p><small>{g.id} · Submitted {day(g.created_at)}{g.worker?" · Handled by "+g.worker:""}</small></div>{g.status==="Awaiting Confirmation"&&<div className="report-actions"><button onClick={()=>onAction(g.id,"Needs Work Again")}>Not satisfied</button><button className="close" onClick={()=>onAction(g.id,"Completed")}>Resolved ✓</button></div>}</article>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
